# This workflow adds the To Triage label to new issues by default.
# It is based on this example in the GitHub documentation: https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues
name: Triage Labels
on:
  issues:
    types:
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        if: contains( github.event.issue.labels.*.name.startsWith("[zube]"), false)
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "[zube]: To Triage"
          repo-token: ${{ secrets.GITHUB_TOKEN }}