# This workflow adds the To Triage label to new issues by default.
# It is based on this example in the GitHub documentation: https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues
name: Triage Labels
on:
  issues:
    types:
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        if: "!(contains(github.event.issue.labels.*.name, '[zube]: Working') || contains(github.event.issue.labels.*.name, '[zube]: Backlog') || contains(github.event.issue.labels.*.name, '[zube]: Backend Blocked') || contains(github.event.issue.labels.*.name, '[zube]: Next Up') || contains(github.event.issue.labels.*.name, '[zube]: Review'))"
        uses: github/issue-labeler@v2.5
        with:
          add-labels: "[zube]: To Triage"
          repo-token: ${{ secrets.GITHUB_TOKEN }}